version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: pokemoney-mysql
    environment:
      MYSQL_DATABASE: pokemoney
      MYSQL_USER: coder
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

